apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec-deployment
  labels:
    app: ec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ec
  template:
    metadata:
      labels:
        app: ec
    spec:
      containers:
      - name: app
        image: ec-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: ec-secret
                key: OPENAI_API_KEY
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: ec-config
---
apiVersion: v1
kind: Service
metadata:
  name: ec-service
spec:
  selector:
    app: ec
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
