# permissions for end users to edit embedchainapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: embedchainapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: embedchainapp-editor-role
rules:
- apiGroups:
  - aiapps.learncloudnative.com
  resources:
  - embedchainapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiapps.learncloudnative.com
  resources:
  - embedchainapps/status
  verbs:
  - get
