---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - aiapps.learncloudnative.com
  resources:
  - embedchainapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiapps.learncloudnative.com
  resources:
  - embedchainapps/finalizers
  verbs:
  - update
- apiGroups:
  - aiapps.learncloudnative.com
  resources:
  - embedchainapps/status
  verbs:
  - get
  - patch
  - update
