---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-aiapps-learncloudnative-com-v1-embedchainapp
  failurePolicy: Fail
  name: membedchainapp.kb.io
  rules:
  - apiGroups:
    - aiapps.learncloudnative.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - embedchainapps
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-aiapps-learncloudnative-com-v1-embedchainapp
  failurePolicy: Fail
  name: vembedchainapp.kb.io
  rules:
  - apiGroups:
    - aiapps.learncloudnative.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - embedchainapps
  sideEffects: None
